jenkintestaddd

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -23,6 +23,11 @@ pipeline {
             steps {
                 sh'''
                   echo "test stage"
+                  if test -f "build/index.html"; then
+                        echo "✅ index.html exists."
+                    else
+                        echo "❌ index.html not found!"
+                        exit 1
                 '''
             }
         }
