htmll

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,112 +1,192 @@
+// pipeline {
+//     agent any
+//     stages {
+//         /*stage('Build') {
+//             agent {
+//                 docker{
+//                     image 'node:18-alpine'
+//                     reuseNode true
+//                 }
+//             }
+//             steps {
+//                 sh'''
+//                   ls -la
+//                   node --version
+//                   npm --version
+//                   npm ci
+//                   npm run build
+//                   ls -la
+//                 '''
+//             }
+//         }*/
+//     //     stage("Test") {
+//     //         agent {
+//     //             docker {
+//     //                 image 'node:18-alpine'
+//     //                 reuseNode true
+//     //             }
+//     //         }
+//     //         steps {
+//     //             sh'''
+//     //               echo "test stage"
+//     //               if test -f "build/index.html"; then
+//     //                     echo "✅ index.html exists."
+//     //                 else
+//     //                     echo "❌ index.html not found!"
+//     //                     exit 1
+//     //                 fi
+//     //               #npm test
+//     //             '''
+//     //         }
+//     //     }
+//     //     stage("E2E") {
+//     //         agent {
+//     //             docker {
+//     //                 image 'mcr.microsoft.com/playwright:v1.56.0-noble'
+//     //                 reuseNode true
+//     //             }
+//     //         }
+//     //         steps {
+//     //             sh'''
+//     //               npm install serve
+//     //               node_modules/.bin/serve -s build &
+//     //               sleep 10
+//     //               npx playwright test
+//     //             '''
+//     //         }
+//     //     }
+//     // }
+//     stages('run tests') {
+//         parallel {
+//                 stage("Test") {
+//                 agent {
+//                     docker {
+//                         image 'node:18-alpine'
+//                         reuseNode true
+//                     }
+//                 }
+//                 steps {
+//                     sh'''
+//                     echo "test stage"
+//                     if test -f "build/index.html"; then
+//                             echo "✅ index.html exists."
+//                         else
+//                             echo "❌ index.html not found!"
+//                             exit 1
+//                         fi
+//                     #npm test
+//                     '''
+//                 }
+//                 post {
+//                     always {
+//                         publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright HTML Report', reportTitles: '', useWrapperFileDirectly: true])
+//                     }
+//                 }
+//             }
+//             stage("E2E") {
+//                 agent {
+//                     docker {
+//                         image 'mcr.microsoft.com/playwright:v1.56.0-noble'
+//                         reuseNode true
+//                     }
+//                 }
+//                 steps {
+//                     sh'''
+//                     npm install serve
+//                     node_modules/.bin/serve -s build &
+//                     sleep 10
+//                     npx playwright test
+//                     '''
+//                 }
+//             }
+
+//         }
+//     }
+//     //post {
+//       //  always {
+//      //       archiveArtifacts allowEmptyArchive: true, artifacts: '**/jest-results/junit.xml'
+//          //   #junit 'jest-results/junit.xml'
+//        //     #sh 'ls -la jest-results'
+//        // }
+//    // }
+// }
+
+
+
 pipeline {
     agent any
+
     stages {
-        /*stage('Build') {
+        /*
+
+        stage('Build') {
             agent {
-                docker{
+                docker {
                     image 'node:18-alpine'
                     reuseNode true
                 }
             }
             steps {
-                sh'''
-                  ls -la
-                  node --version
-                  npm --version
-                  npm ci
-                  npm run build
-                  ls -la
+                sh '''
+                    ls -la
+                    node --version
+                    npm --version
+                    npm ci
+                    npm run build
+                    ls -la
                 '''
             }
-        }*/
-    //     stage("Test") {
-    //         agent {
-    //             docker {
-    //                 image 'node:18-alpine'
-    //                 reuseNode true
-    //             }
-    //         }
-    //         steps {
-    //             sh'''
-    //               echo "test stage"
-    //               if test -f "build/index.html"; then
-    //                     echo "✅ index.html exists."
-    //                 else
-    //                     echo "❌ index.html not found!"
-    //                     exit 1
-    //                 fi
-    //               #npm test
-    //             '''
-    //         }
-    //     }
-    //     stage("E2E") {
-    //         agent {
-    //             docker {
-    //                 image 'mcr.microsoft.com/playwright:v1.56.0-noble'
-    //                 reuseNode true
-    //             }
-    //         }
-    //         steps {
-    //             sh'''
-    //               npm install serve
-    //               node_modules/.bin/serve -s build &
-    //               sleep 10
-    //               npx playwright test
-    //             '''
-    //         }
-    //     }
-    // }
-    stages('run tests') {
-        parallel {
-                stage("Test") {
-                agent {
-                    docker {
-                        image 'node:18-alpine'
-                        reuseNode true
-                    }
-                }
-                steps {
-                    sh'''
-                    echo "test stage"
-                    if test -f "build/index.html"; then
-                            echo "✅ index.html exists."
-                        else
-                            echo "❌ index.html not found!"
-                            exit 1
-                        fi
-                    #npm test
-                    '''
-                }
-                post {
-                    always {
-                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright HTML Report', reportTitles: '', useWrapperFileDirectly: true])
-                    }
-                }
-            }
-            stage("E2E") {
-                agent {
-                    docker {
-                        image 'mcr.microsoft.com/playwright:v1.56.0-noble'
-                        reuseNode true
-                    }
-                }
-                steps {
-                    sh'''
-                    npm install serve
-                    node_modules/.bin/serve -s build &
-                    sleep 10
-                    npx playwright test
-                    '''
-                }
-            }
+        }
+        */
 
+        stage('Tests') {
+            parallel {
+                stage('Unit tests') {
+                    agent {
+                        docker {
+                            image 'node:18-alpine'
+                            reuseNode true
+                        }
+                    }
+
+                    steps {
+                        sh '''
+                            #test -f build/index.html
+                            npm test
+                        '''
+                    }
+                    post {
+                        always {
+                            junit 'jest-results/junit.xml'
+                        }
+                    }
+                }
+
+                stage('E2E') {
+                    agent {
+                        docker {
+                            image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
+                            reuseNode true
+                        }
+                    }
+
+                    steps {
+                        sh '''
+                            npm install serve
+                            node_modules/.bin/serve -s build &
+                            sleep 10
+                            npx playwright test  --reporter=html
+                        '''
+                    }
+
+                    post {
+                        always {
+                            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright HTML Report', reportTitles: '', useWrapperFileDirectly: true])
+                        }
+                    }
+                }
+            }
         }
     }
-    //post {
-      //  always {
-     //       archiveArtifacts allowEmptyArchive: true, artifacts: '**/jest-results/junit.xml'
-         //   #junit 'jest-results/junit.xml'
-       //     #sh 'ls -la jest-results'
-       // }
-   // }
 }
+
